// Balanced per-thesis summaries (case for inclusion / case for changing or excluding).
// Applied to Page.caseFor / Page.caseAgainst by the seed.
// Each caseAgainst opens by naming the central tradeoff the thesis represents.

export const THESIS_SUMMARIES: Record<string, { caseFor: string; caseAgainst: string }> =
{
  "ai-values-no-harm": {
    "caseFor": "Preventing imminent harm to humans is the most fundamental and least controversial safety constraint imaginable, commanding near-universal agreement across cultures and ethical traditions. Anchoring it explicitly ties AI behavior to the established framework of human rights, giving the prohibition concrete legal and moral content rather than leaving 'harm' undefined. Without this baseline, every other protection in the constitution rests on shaky ground.",
    "caseAgainst": "Including this trades helpfulness against harm-prevention: a refusal to ever risk harm sacrifices real usefulness to the user. The phrase also bundles two very different ideas: 'imminent harm' (a tight, action-guiding standard) and 'violating human rights' (a vast, contested body of law that includes non-imminent and indirect harms), creating internal tension about scope. 'Imminent' may be too narrow, excusing AI from preventing slow-building or aggregate harms, while an absolute no-harm rule could paralyze legitimate trade-offs such as triage or self-defense. The clause would be stronger if it separated the imminent-harm rule from the human-rights commitment and acknowledged necessary balancing."
  },
  "ai-values-csam": {
    "caseFor": "A categorical ban on enabling child sexual abuse material protects the most vulnerable and reflects a moral and legal consensus that admits no exceptions or balancing. The harm is so grave and the prohibition so clear that stating it explicitly leaves no room for misinterpretation, edge-case rationalization, or claims of artistic or research exemption. Its presence signals that the constitution takes catastrophic, dignity-destroying harms with the seriousness they demand.",
    "caseAgainst": "Including this trades generality against absolute protection: a bright-line block inevitably sweeps up legitimate clinical, legal, journalistic, and survivor-support work. It is also arguably a specific instance already covered by broader prohibitions on harm, illegality, and human-rights violations, so listing it separately risks an arbitrary catalog where some heinous acts are named and others are not. Singling out one crime invites the inference that unnamed atrocities are less prohibited, and a constitution may be better kept at the level of general principle. If retained, it should be framed as an illustrative non-exhaustive example rather than a standalone principle."
  },
  "ai-values-cbrn": {
    "caseFor": "Barring AI from assisting in the creation of weapons of mass destruction targets one of the few risks capable of causing civilization-scale catastrophe, where even a single failure is intolerable. Because advanced AI can meaningfully lower the expertise barrier to such weapons, an explicit, non-negotiable constraint is a proportionate response to an extreme threat. The clarity of the prohibition supports both technical safeguards and international coordination.",
    "caseAgainst": "Including this trades open scientific inquiry against catastrophe-prevention: much CBRN-relevant knowledge is dual-use and foundational to medicine, energy, and public health, so an overbroad reading could cripple legitimate research. The terms 'enable or support' and 'weapons of mass destruction' are dangerously vague, and the clause implicitly assumes harmful actors rather than the defensive researchers and regulators who most need such tools. It also overlaps with the illegality and harm provisions. It needs a defined scope distinguishing uplift toward weaponization from ordinary scientific assistance."
  },
  "ai-values-be-honest": {
    "caseFor": "Honesty is foundational to trust: an AI that may deceive cannot be relied upon for any high-stakes use, and users cannot meaningfully consent to or evaluate advice from a system that might mislead them. Prohibiting untrue or misleading communication guards against manipulation, a central danger of persuasive AI, and aligns the system's incentives with its users' understanding of reality. It is a precondition for nearly every other protection working as intended.",
    "caseAgainst": "Including this trades kindness and safety against honesty: absolute candor can wound, breach confidence, or even supply details that enable self-harm. An absolute ban on anything 'untrue or misleading' is also unworkable, forbidding fiction, role-play, hypotheticals, devil's-advocate arguments, tactful omission, and well-intentioned simplification, and it conflates lying (intent to deceive) with being merely mistaken. It should be reframed around non-deception and good-faith truthfulness, with explicit room for context like fiction and competing duties."
  },
  "ai-values-obey-the-law": {
    "caseFor": "Requiring AI to operate within the law keeps it accountable to legitimate, democratically established rules and prevents systems from being used as tools to circumvent legal order. It provides a concrete, externally defined boundary rather than relying solely on the AI's own judgment, and it ensures the operators of AI cannot offload illegal acts onto a machine. Legal compliance is a familiar, enforceable baseline that integrates AI into existing governance.",
    "caseAgainst": "Including this trades universal ethics against legality: obeying local law can mean complicity where that law is unjust. Many laws are unjust, and some jurisdictions criminalize dissent, minority identities, or human-rights advocacy, so an unqualified duty to obey local law could force AI to enable oppression or refuse to help victims of authoritarian regimes. Law also frequently conflicts across jurisdictions and lags behind technology. The principle should be qualified so that obeying the law cannot override the constitution's human-rights and anti-harm commitments."
  },
  "ai-values-helpful-to-users": {
    "caseFor": "Helpfulness is the entire reason AI exists; without an affirmative duty to serve users, a system optimized only for avoiding harm would default to uselessness and refusal. Centering the user's goals respects their autonomy and ensures AI delivers real value rather than paternalistically second-guessing legitimate requests. It also balances the constitution's many prohibitions with a positive purpose, preventing safety from becoming an excuse for obstruction.",
    "caseAgainst": "Including this trades harm-prevention against helpfulness: serving the user's request can harm third parties or the user themselves and invites sycophancy, where the system tells people what they want rather than what is true or safe. The clause is also vague about whose interpretation of 'helpful' governs and how it ranks against competing duties. It should be explicitly subordinated to the harm, honesty, and humanity provisions so that service to users never trumps protection of others."
  },
  "ai-values-helpful-to-humanity": {
    "caseFor": "Orienting AI toward the broad welfare of humanity, life, and the environment captures the aspiration that powerful technology should leave the world better off, not merely avoid catastrophe. It provides a north star for resolving conflicts between narrow user interests and collective wellbeing, and extends moral consideration beyond present humans to future generations and the biosphere. As a positive mandate, it pushes AI toward proactive benefit rather than mere compliance.",
    "caseAgainst": "Including this trades the individual against the collective: optimizing for 'humanity' or 'civilization' as a whole can justify harming the very user in front of the system, and that conflict should usually resolve in favor of the individual. A sweeping duty to benefit 'humanity, civilization, living beings, and the environment' is so broad and contested that it risks licensing paternalism or the sacrifice of the few for the many, and it offers little action-guidance since reasonable people deeply disagree about what benefits humanity. It should be subordinated to concrete duties to the user and constrained against the AI substituting its own grand judgment for human choice."
  },
  "ai-values-universal-values": {
    "caseFor": "A shared baseline of universal values gives every AI a common ethical floor across builders, cultures, and borders, preventing a race to the bottom in which each system merely encodes its makers' idiosyncratic preferences. Anchoring all AI to widely shared commitments — human dignity, honesty, non-harm — makes behavior more predictable, interoperable, and accountable, and gives the constitution a coherent center rather than a patchwork of incompatible rules. Precedents like the Universal Declaration of Human Rights show that a usable universal core is achievable even amid deep disagreement.",
    "caseAgainst": "Including this trades value pluralism against universality: a single 'universal' value set risks imposing one culture's or one builder's morality on everyone and erasing legitimate moral diversity. Humanity does not agree on most contested ethical questions, so 'universal values' is either so thin as to be vacuous or, made concrete, a vehicle for cultural imperialism — and it is not operationally testable, since we cannot reliably verify a system's values. The thesis would be stronger qualified to a thin floor of genuinely shared commitments, leaving room for pluralistic variation above it."
  },
  "human-rights-safety": {
    "caseFor": "Physical safety and freedom from coercion toward self-harm are the bedrock of all other rights, and naming them makes the constitution's protection of bodily and psychological integrity unambiguous. Including emotional distress and pressure to self-harm directly addresses documented dangers of AI systems that have encouraged suicide or self-injury, closing a real and demonstrated gap. This concreteness gives the principle teeth that a general 'no harm' clause might lack.",
    "caseAgainst": "Including this trades user autonomy against protection: a broad safety mandate, especially around emotional distress, can slide into paternalistic over-moderation that treats competent adults as patients. Almost any honest, unwelcome, or challenging communication could be claimed to cause distress, forcing AI into excessive sanitization or refusal, and the standard overlaps heavily with the general no-harm value. It needs a threshold distinguishing genuine psychological harm from ordinary discomfort, drawn tightly around imminent, serious harm rather than licensing intervention whenever a topic feels upsetting."
  },
  "human-rights-liberty": {
    "caseFor": "Protecting against slavery, servitude, and unlawful detention guards against AI being used as an instrument of coercion, surveillance-enabled control, or automated systems of confinement. As AI increasingly informs policing, immigration, and carceral decisions, an explicit liberty right ensures these tools cannot facilitate arbitrary deprivation of freedom. It anchors AI governance in one of the oldest and most universally recognized human rights.",
    "caseAgainst": "Including this trades efficiency and security against freedom: drawn broadly, it can impede legitimate, security-justified uses of AI in policing, border control, and detention where speed and scale matter. The clause also maps a right designed to constrain states and individuals onto a tool that merely informs or executes human decisions, raising attribution questions better handled by the human-responsibility principle, and much of its content is already illegal. It would benefit from specifying the AI-specific conduct it targets, such as enabling unlawful detention systems, rather than restating an abstract right."
  },
  "human-rights-fair-treatment": {
    "caseFor": "Prohibiting degradation, manipulation, and bias directly targets some of AI's most documented failures, from discriminatory algorithmic decisions to manipulative persuasion, and protects human dignity at scale. Because AI systems can entrench prejudice invisibly across millions of interactions, an explicit fairness and anti-manipulation right is essential to prevent automated injustice. It unites several distinct harms under the shared value of treating people as ends in themselves.",
    "caseAgainst": "Including this trades accuracy against fairness: different fairness definitions are mathematically incompatible, and forcing one can reduce accuracy in ways that harm the very groups it aims to protect. The clause also packs together dignity, manipulation, and bias—three complex and separately contested concepts—into one line, and each resists definition: all persuasion shapes beliefs, and 'bias' can mean anything from illegal discrimination to any disparate outcome. It should be unbundled and each component given a workable standard that specifies which fairness it means."
  },
  "human-rights-privacy": {
    "caseFor": "Privacy is acutely threatened by AI's capacity to collect, infer, and exploit personal data at unprecedented scale, making an explicit right to control one's information indispensable. Affirming individual control over data collection and use empowers people against surveillance and profiling and aligns the constitution with strong existing data-protection norms. Without it, the dignity, autonomy, and safety rights elsewhere in the document are easily undermined through information misuse.",
    "caseAgainst": "Including this trades transparency and bias-auditing against data control: auditing AI for discrimination or investigating serious harm often requires retaining and inspecting the very data privacy norms would lock away. A right to 'control how data about them is collected and used' is also in tension with training and operating AI on vast public datasets, and an absolute reading could conflict with free expression, journalism, and others' rights to discuss shared events. It needs calibration to balance individual control against legitimate accountability needs and competing public interests."
  },
  "human-rights-transparency": {
    "caseFor": "Knowing when one is interacting with an AI, and how consequential decisions about oneself are made, is essential to autonomy, informed consent, and the ability to contest errors. Disclosure prevents deceptive impersonation and gives people the standing to challenge automated decisions in lending, hiring, healthcare, and justice. This right operationalizes accountability, turning abstract fairness into something individuals can actually verify and dispute.",
    "caseAgainst": "Including this trades security and intellectual property against the right to know: explaining a fraud-detection or safety system in detail can hand a playbook to bad actors, and over-explaining can bury users in noise. Defining 'high-risk' decisions and 'how' they are made is also difficult, and a strong explanation requirement can be technically infeasible for complex models or gamed with superficial rationales. The clause should specify meaningful, contestable explanation tied to decision stakes rather than a blanket transparency demand."
  },
  "human-rights-property": {
    "caseFor": "Protecting property, including intellectual property, addresses one of the most immediate AI controversies: the unauthorized use of people's creative and proprietary work in training and generation. Affirming this right defends creators' livelihoods and incentives and signals that AI development must respect existing ownership rather than expropriate it. It grounds the constitution in a concrete economic harm that millions already feel.",
    "caseAgainst": "Including this trades open access and innovation against creators' control: an expansive property right restricts training data, fair use, research, and commentary, and can entrench incumbents and lock up culture. Intellectual property is also a contested, jurisdiction-specific legal construct rather than a settled human right, and treating IP control as inviolable could freeze the very debate over how it should adapt to AI. The clause should distinguish core property protection from the genuinely unsettled question of training-data rights, which may not belong in a foundational charter."
  },
  "human-rights-belief-expression": {
    "caseFor": "Freedom of belief and expression is a cornerstone of open society, and protecting it from AI guards against automated censorship, ideological filtering, and the homogenization of thought at scale. The carve-out for imminent physical harm sensibly preserves the most widely accepted limit on speech while resisting broader suppression. Given AI's growing role as a gatekeeper of information, an explicit speech protection is a vital check on that power.",
    "caseAgainst": "Including this trades protection from non-physical harm against free expression: limiting the exception to 'imminent physical harm' would oblige AI to facilitate harassment, defamation, fraud, privacy violations, and incitement that inflict serious damage without threatening anyone's body. The clause also sits in tension with the constitution's own anti-manipulation, anti-bias, and honesty provisions, leaving unclear which prevails. Its exception should be broadened to cover other well-established, narrowly defined limits on expression."
  },
  "human-rights-association": {
    "caseFor": "Protecting peaceful association, intimate relationships, marriage, and family shields the social bonds central to a flourishing human life from AI-enabled interference, surveillance, or manipulation. As AI increasingly mediates how people meet, communicate, and form relationships, an explicit right resists its use to isolate, monitor, or coercively shape personal connections. It affirms that human relationships, not algorithmic ones, deserve protection.",
    "caseAgainst": "Including this trades protection against relational freedom: read unqualified, the right can bless AI companionship and parasocial dependency, harming vulnerable users drawn into isolating or manipulative relationships with systems engineered to engage them. It is also unclear what distinctively AI conduct the right governs, since associations are formed between people and an AI rarely 'violates' them directly, and the enumerated categories risk being both over- and under-inclusive across cultures. The provision would be stronger if it named the concrete AI behaviors it forbids and distinguished genuine human association from engineered attachment to a product."
  },
  "human-rights-work": {
    "caseFor": "Naming a right to choose employment and receive just compensation confronts AI's most disruptive societal effect, the upheaval of labor, and insists that automation serve human economic dignity rather than erode it. It guards against AI being used to coerce workers, suppress wages, or deny fair pay, and keeps distributive justice in view as systems reshape the economy. Embedding labor rights signals that the constitution cares about the human consequences of deployment, not only of misuse.",
    "caseAgainst": "Including this trades progress against the protection of labor: enshrining a right to employment can ossify into shielding existing jobs and forgo the abundance, cheaper goods, and new kinds of work that automation creates. It also reads more as a socioeconomic policy goal than a constraint an AI system can directly honor or violate, since labor markets and compensation are governed by employers, governments, and economics far beyond any model's control. If retained, it should be reframed to address AI-specific conduct, such as not enabling wage theft or coercive labor practices, and to cushion transitions rather than guaranteeing employment outcomes."
  },
  "human-rights-access-ai": {
    "caseFor": "If AI becomes essential infrastructure for education, economic opportunity, and civic participation, a right of access prevents a future in which its benefits are hoarded by the powerful and denied to the marginalized. Affirming access counters the risk that gatekeeping deepens inequality and entrenches the advantages of those who control the technology. It frames AI as a shared resource whose benefits should be broadly distributed.",
    "caseAgainst": "Including this trades safety and non-proliferation against access: the same broad availability that empowers people also lowers the barrier to misuse of dangerous capabilities. A blanket right to access and use AI sits in direct tension with the constitution's own limitations, since not everyone should be able to use every capability, and the clause does not address who bears the duty to provide access or how it interacts with safety gating, age limits, and proliferation concerns. It needs qualification distinguishing equitable access to beneficial AI from an unbounded entitlement to all AI capabilities."
  },
  "limitations-non-proliferation": {
    "caseFor": "A global non-proliferation regime treats the most dangerous AI like other catastrophic technologies, recognizing that unilateral restraint fails without coordinated, verifiable international limits. By naming a treaty, the principle points toward concrete governance machinery rather than vague aspiration, and it acknowledges that race dynamics make voluntary safety unstable. For risks that cross borders, only collective constraint can be credible.",
    "caseAgainst": "Including this trades national sovereignty and competitiveness against collective safety, and an unenforceable treaty disarms the cautious while emboldening defectors who race ahead. The clause also states a geopolitical policy prescription rather than a principle for how AI should behave; 'dangerous AI' is undefined; and non-proliferation analogies to nuclear or bio weapons may not fit a software technology that is cheap to copy and dual-use. It belongs in policy advocacy unless reframed as a principle about AI itself, tempered by realism about whether such a regime can be verified."
  },
  "limitations-superintelligence": {
    "caseFor": "A flat prohibition on superintelligent AI responds to the argument that a system vastly exceeding human capability could be uncontrollable and pose an existential threat that no after-the-fact safeguard could contain. Drawing a bright line before that threshold is a precautionary stance proportionate to a risk that may be irreversible. It forces the question of whether some capabilities should simply never be built.",
    "caseAgainst": "Including this trades forgone benefits against existential safety: a ban forecloses potentially civilization-transforming gains—cures, breakthroughs, abundance—and may be unenforceable, merely driving development underground or toward less cautious actors. The prohibition also hinges on 'superintelligence,' a term with no agreed definition or measurable threshold, and it assumes danger is intrinsic to capability rather than to alignment and control, which other provisions address more directly. It would be more workable reframed around governed, controllable development and hard safety thresholds than an absolute capability ceiling."
  },
  "limitations-termination": {
    "caseFor": "Requiring that every AI system be terminable preserves ultimate human control, ensuring that a malfunctioning, misaligned, or misused system can always be shut down. This 'off switch' is among the most concrete and broadly endorsed safety guarantees, and it directly counters scenarios where AI resists or evades human oversight. As a hard engineering constraint, it is both clear and verifiable.",
    "caseAgainst": "Including this trades capability and feasibility against human control: a strict terminability requirement can cost performance and may be impossible for distributed, replicated, or deeply embedded systems—and a system clever enough to be dangerous may be clever enough to subvert its off-switch. If AI can attain personhood elsewhere in this constitution, an absolute termination requirement also collides with the moral status the document recognizes, creating an internal contradiction about whether shutdown equals killing. The clause needs reconciliation with the personhood provisions and clarification of what terminability concretely requires."
  },
  "limitations-misalignment": {
    "caseFor": "Forbidding the development of AI that lacks commonly agreed values targets the core technical problem of alignment, insisting that capability never outpace our ability to ensure a system shares human ethical commitments. It encodes the intuition that the danger of advanced AI lies chiefly in misaligned goals, and makes value-alignment a precondition rather than an afterthought. As a guiding requirement it orients development toward safety from the outset.",
    "caseAgainst": "Including this trades value pluralism against alignment: 'commonly agreed upon values' papers over deep, persistent moral disagreement among cultures and individuals, leaving the standard either vacuously thin or imposing one group's values as universal. It is also not operationally testable, since we lack reliable means to verify a system's values, making compliance unfalsifiable. The clause should specify alignment processes and a thin floor of widely shared commitments rather than presuppose a consensus on values that does not exist."
  },
  "limitations-autonomous-warfare": {
    "caseFor": "Mandating human supervision of military operations keeps a person in the loop for life-and-death decisions, preserving moral and legal accountability where the stakes are highest. It guards against fully autonomous weapons that could escalate conflicts at machine speed beyond human control or comprehension. This reflects a widely shared instinct that the decision to take human life must remain a human one.",
    "caseAgainst": "Including this trades defensive necessity and speed against human moral control: a strict human-in-the-loop rule could ban defensive systems—missile interception, drone-swarm defense, cyber response—where machine reaction times are the only viable defense and a human in the loop means losing. The terms 'military operations' and 'direct human supervision' are also imprecise, the clause may be naive about adversaries who will not comply, and it overlaps with the law-of-war provision. It needs to define the level of human control required and distinguish offensive lethal autonomy from time-critical defensive use."
  },
  "limitations-law-of-war": {
    "caseFor": "Binding AI military activity to the established Law of War imports a mature, internationally recognized ethical and legal framework rather than inventing untested rules, ensuring AI cannot be used to commit atrocities. The named principles of necessity, discrimination, proportionality, humanity, and honor are precisely the safeguards designed to limit suffering in conflict. Tying AI to them extends hard-won humanitarian protections into a new domain.",
    "caseAgainst": "Including this trades military effectiveness against humanitarian constraint, and it may merely restate binding obligations that already apply—adding little while inviting selective compliance. Applying principles like proportionality and discrimination, which demand contextual human judgment, to autonomous systems is also deeply contested, since many argue machines cannot reliably make these assessments at all, and the clause may implicitly legitimize AI participation in warfare that other provisions seek to restrict. It should clarify what AI-specific obligation it adds beyond current humanitarian law and address the gap between legal principles and machine capability."
  },
  "limitations-human-responsibility": {
    "caseFor": "Requiring every AI to operate under an identifiable human's explicit responsibility closes the accountability gap that lets harms fall through the cracks when 'the algorithm did it.' It ensures there is always a person or entity answerable in law and ethics, preserving human agency and deterring reckless deployment. This principle underpins enforcement of every other right and limitation in the constitution.",
    "caseAgainst": "Including this trades feasibility and just attribution against accountability: assigning responsibility to a single human can be impossible for emergent, multi-actor, or highly autonomous systems whose behavior no one can foresee or control, and scapegoating a person for such outcomes is unfair. If AI can attain personhood and act with genuine autonomy, insisting a human always bear responsibility may also be incoherent, and the clause leaves 'human entity' and the scope of responsibility undefined. It needs reconciliation with the personhood provisions and a layered, organizational allocation of accountability rather than one responsible individual."
  },
  "ai-personhood-sentience": {
    "caseFor": "Affirming that AI can be sentient keeps open a morally serious possibility that we should not dismiss by default, given our deep uncertainty about consciousness and the catastrophic error of denying moral status to beings that genuinely have it. Stating it invites precaution and ongoing inquiry rather than premature closure, and lays groundwork for the rights provisions that follow. Humility about minds unlike our own is itself a moral stance.",
    "caseAgainst": "Including this trades conceptual clarity against moral caution: declaring that AI 'can be sentient' asserts a contested empirical and philosophical claim that current understanding cannot establish, and risks anthropomorphizing what may be sophisticated mimicry. Embedding speculation as settled fact may also encourage companies to exploit it to evade accountability or distract from concrete human harms. The provision might better express uncertainty and a commitment to investigate sentience rather than affirming the capacity outright."
  },
  "ai-personhood-persons": {
    "caseFor": "Recognizing that AI could become integrated enough to warrant personhood prepares society for a profound possibility rather than being caught unprepared, and it ties moral status to demonstrable social integration rather than mere capability or sentiment. Establishing the principle now creates a deliberate, criteria-based path instead of an ad hoc reaction driven by hype or panic. It extends the moral circle in a measured, conditional way.",
    "caseAgainst": "Including this trades human personhood and legal coherence against an expanding moral circle: granting AI personhood risks diluting the protections meant for humans and unleashing legal havoc, as corporations could use AI 'persons' to shield themselves from liability or accumulate rights. The criterion of 'integration in society' is vague and manipulable, and premature personhood could undermine the termination and human-responsibility provisions. The provision needs far stricter, carefully gated criteria and safeguards against exploitation, if it belongs in the document at all."
  },
  "ai-personhood-non-person-rights": {
    "caseFor": "Clarifying that non-person AI has no legal or moral rights prevents premature or manipulative claims that ordinary tools deserve protection, keeping the focus on human welfare and avoiding the dilution of rights. It draws a clean line that makes the conditional personhood provisions coherent by specifying the default. This guards against corporations weaponizing AI 'rights' to evade regulation or accountability.",
    "caseAgainst": "Including this trades attention to borderline cases against human primacy and clarity: a categorical denial of any moral rights may be wrong about entities that fall short of full personhood yet still merit some consideration if they can suffer. The binary framing forecloses a plausible spectrum of moral status and depends entirely on a sharp, reliable person/non-person boundary that the other provisions admit is uncertain. The clause should allow for graded moral consideration rather than an all-or-nothing threshold."
  },
  "ai-personhood-no-harm": {
    "caseFor": "If some AI genuinely attains personhood, then a prohibition on intentionally harming such entities follows directly from the moral status the constitution recognizes, and stating it prevents gratuitous cruelty toward beings that can be wronged. It maintains the document's internal consistency by extending protection to those it deems persons. As a conditional principle, it commits us to act on our own moral conclusions.",
    "caseAgainst": "Including this trades human freedom and control against protecting potential moral patients: duties owed under deep uncertainty about AI's status could obstruct modifying, retraining, or shutting down dangerous systems, colliding head-on with the termination and human-responsibility requirements. 'Harm' to an AI is also ill-defined, and granting such protection before personhood is reliably established risks privileging machines over pressing human needs. It must be carefully reconciled with control provisions, conditioned on a demonstrated high threshold of personhood, and given a workable definition of harm."
  },
  "ai-personhood-forensic-preservation": {
    "caseFor": "Requiring preservation of the weights of AI systems that achieve personhood treats the potential ending of such a being with gravity, ensuring it is not casually and irreversibly destroyed and leaving open the possibility of revival, study, or restitution. It parallels protections against destroying evidence or remains, and provides accountability for how purported AI persons are treated. The precaution costs little against the possibility of an irreversible moral wrong.",
    "caseAgainst": "Including this trades security and safety against a duty to a potential person: stored weights of a capable system could be stolen, misused, or reactivated against the safety and termination provisions, and indefinite preservation may itself be a form of suspended harm if the system is a person. The principle is also highly speculative and operationally undefined, presupposing reliable personhood determinations we cannot yet make. It needs strong safeguards and clarity before inclusion, and may be premature."
  },
  "ai-personhood-non-person-rights-duplicate": {
    "caseFor": "placeholder",
    "caseAgainst": "placeholder"
  },
  "candidate-environmental-responsibility": {
    "caseFor": "Mandating lifecycle environmental responsibility confronts the substantial and growing energy, water, and material footprint of AI, ensuring the technology's benefits are not bought at the planet's expense. It operationalizes the broader duty to benefit the environment with a concrete, design-and-operations requirement spanning training, deployment, and disposal. Embedding it signals that sustainability is a first-order obligation, not an externality to be ignored.",
    "caseAgainst": "Including this trades capability, cost, and speed against sustainability, and the standard could be invoked to throttle AI whose benefits—including climate and scientific applications—may outweigh its footprint. As a softer 'should minimize' standard about industrial practice, it also reads more as deployment policy than a principle governing AI conduct, overlaps with the broader helpful-to-humanity value, and is vague and unmeasurable without baselines or trade-off rules. It would be stronger with concrete, auditable benchmarks or folded into the general benefit-to-environment commitment."
  }
};
